name: Penn-Marketplace CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd backend && npm install
      - run: cd backend && npm run test
      - run: cd backend && npm run lint
      - run: cd frontend && npm install
      - run: cd frontend && npm run test
      - run: cd frontend && npm run lint
